### ISSUE TITLE
some menu items will not highlight

### ISSUE THREAD

**Issue by scs-vuw** [zwbetz-gh/vanilla-bootstrap-hugo-theme#18]
**Describe the bug**
Hi there, I'm making a basic site with this theme (thank you). I'm having an issue where three of my menu items will not highlight when active (submit abstract, registration, and program). I'm not very sure why this is only happening for those three menu items, any ideas?

Here is my site: https://ahsn-conference-2021.netlify.com/

Here is my yaml menu:

```
menu:
  nav:
  - name: Welcome
    pre: home
    url: /
    weight: 1
  - name: Venue and Travel
    pre: map
    url: /venue/
    weight: 2
  - name: Keynote Speakers
    pre: message-circle 
    url: /keynotes/
    weight: 3
  - name: Submit Abstract
    pre: clipboard
    url: /abstract-submission/
    weight: 4
  - name: Registration
    pre: user-plus
    url: /registration/
    weight: 5
  - name: Program
    pre: book-open
    url: /program/
    weight: 6
  - name: Contact
    pre: help-circle
    url: /contact/
    weight: 7
```
